/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package forme;

import controller.Controller;
import java.util.List;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Autor;
import model.Knjiga;
import model.Zanr;

/**
 *
 * @author PC
 */
public class FormaKnjiga extends javax.swing.JDialog {
    private Controller kontroler;
    private GlavnaForma gf;
    private Knjiga knjigaZaIzmenu;

    /** Creates new form FormaKnjiga */
    public FormaKnjiga(java.awt.Frame parent, boolean modal,Knjiga knjigazaizmenu) {
        super(parent, modal);
        initComponents();
        kontroler = Controller.getInstance();
        this.gf = (GlavnaForma) parent;
        popuniComboBoxAutorima();
        
        if(knjigazaizmenu!=null){
            this.knjigaZaIzmenu = knjigazaizmenu;
            jTextFieldNaziv.setText(knjigazaizmenu.getNaslov());
            jTextFieldISBN.setText(knjigazaizmenu.getISBN());
            jTextFieldISBN.setEnabled(false);
            jComboBoxAutori.setSelectedItem(knjigazaizmenu.getAutor());
            jComboBoxZanr.setSelectedItem(knjigazaizmenu.getZanr());
            jTextFieldGodinaIzdanja.setText(String.valueOf(knjigazaizmenu.getGodinaIzdanja()));
            jButtonDodaj.setVisible(false);
        } else {
            jButtonIzmeni.setVisible(false);
        }
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxAutori = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldGodinaIzdanja = new javax.swing.JTextField();
        jButtonDodaj = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxZanr = new javax.swing.JComboBox<>();
        jButtonIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv");

        jLabel2.setText("ISBN");

        jLabel3.setText("Autor");

        jComboBoxAutori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAutoriActionPerformed(evt);
            }
        });

        jLabel4.setText("Godina Izdanja");

        jButtonDodaj.setText("DODAJ");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jLabel5.setText("Zanr");

        jComboBoxZanr.setModel(new DefaultComboBoxModel(Zanr.values())
        );

        jButtonIzmeni.setText("IZMENI");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jButtonIzmeni)
                .addGap(50, 50, 50)
                .addComponent(jButtonDodaj)
                .addGap(57, 57, 57)
                .addComponent(jButtonOdustani)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNaziv)
                            .addComponent(jComboBoxAutori, 0, 170, Short.MAX_VALUE)
                            .addComponent(jTextFieldISBN)
                            .addComponent(jTextFieldGodinaIzdanja)
                            .addComponent(jComboBoxZanr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxAutori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldGodinaIzdanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodaj)
                    .addComponent(jButtonOdustani)
                    .addComponent(jButtonIzmeni))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        String naziv = jTextFieldNaziv.getText();
        String isbn = jTextFieldISBN.getText();
        int godIzdanja;
        try{
        godIzdanja = Integer.parseInt(jTextFieldGodinaIzdanja.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Godina izdanja mora biti broj! ","Greska",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Zanr zanr = (Zanr) jComboBoxZanr.getSelectedItem();
        Autor odabraniAutor = (Autor) jComboBoxAutori.getSelectedItem();
        
        Random rand = new Random();
        int id = 101 + rand.nextInt(Integer.MAX_VALUE - 100);
        
        Knjiga novaKnjiga = new Knjiga(id,naziv, odabraniAutor, isbn, godIzdanja, zanr);
        
        kontroler.dodajKnjigu(novaKnjiga); // Controller.getInstance().dodajKnjigu(novaKnjiga)
        gf.osveziTabelu();
        JOptionPane.showMessageDialog(this, "Knjiga je uspesno dodata","Uspesno",JOptionPane.INFORMATION_MESSAGE);
        
        this.dispose();
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        String naziv = jTextFieldNaziv.getText();
        int godIzdanja;
        try{
        godIzdanja = Integer.parseInt(jTextFieldGodinaIzdanja.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Godina izdanja mora biti broj! ","Greska",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Zanr zanr = (Zanr) jComboBoxZanr.getSelectedItem();
        Autor odabraniAutor = (Autor) jComboBoxAutori.getSelectedItem();
        
        knjigaZaIzmenu.setAutor(odabraniAutor);
        knjigaZaIzmenu.setGodinaIzdanja(godIzdanja);
        knjigaZaIzmenu.setNaslov(naziv);
        knjigaZaIzmenu.setZanr(zanr);
        
        kontroler.azurirajKnjigu(knjigaZaIzmenu);
        
        gf.osveziTabelu();
         JOptionPane.showMessageDialog(this, "Knjiga je uspesno izmenjena! ","Uspesno",JOptionPane.INFORMATION_MESSAGE);
            
        this.dispose();
        
        
        
        
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jComboBoxAutoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAutoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAutoriActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JComboBox<Autor> jComboBoxAutori;
    private javax.swing.JComboBox<String> jComboBoxZanr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldGodinaIzdanja;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    
    private void popuniComboBoxAutorima() {
        jComboBoxAutori.removeAllItems();
        //List<Autor> autori = kontroler.getListaAutora();
        List<Autor> autori = Controller.getInstance().ucitajListuAutoraIzBaze();
        for (Autor autor : autori) {
            jComboBoxAutori.addItem(autor);
        }
    }

}
